language: rust
cache: cargo

os:
  - linux
  - osx
  - windows

dist: xenial

rust:
  - stable
  - nightly

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libfuse-dev; fi
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      rustup default "${TRAVIS_RUST_VERSION}-msvc"
      choco install winpcap -y
      wget https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
      unzip WpdPack_4_1_2.zip
      cp WpdPack/Lib/x64/* "$TRAVIS_BUILD_DIR"
    fi

script:
  - cargo build --verbose
  - cargo test --verbose --package rrg-proto --package rrg
  - cargo run -- --version
