language: rust
cache: cargo

os:
  - linux
  - osx
  - windows

dist: xenial

rust:
  - stable
  - nightly

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libfuse-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell -Command "& Install-WindowsFeature -Name Server-Gui-Shell,Server-Gui-Mgmt-Infra -Restart"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then rustup default "${TRAVIS_RUST_VERSION}-msvc"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install winpcap -y; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then tail -n 1000 C:/ProgramData/chocolatey/logs/chocolatey.log; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then wget https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then unzip WpdPack_4_1_2.zip; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cp WpdPack/Lib/x64/* "$TRAVIS_BUILD_DIR"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ls C:/Windows/System32 | grep Packet.dll; fi

script:
  - cargo build --verbose
  - cargo test --verbose --package rrg-proto --package rrg
  - cargo run -- --version
